lib/js_tracker_web/router.ex
defmodule JsTrackerWeb.Router do
  use JsTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BasicAuth, use_config: {:js_tracker, :basic_auth}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", JsTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/targets", TargetController
    resources "/recordings", RecordingController, only: [:index]
    resources "/resources", ResourceController, only: [:index, :show]

  end

  # Other scopes may use custom stacks.
  # scope "/api", JsTrackerWeb do
  #   pipe_through :api
  # end
end

lib/js_tracker/tracker/recording.ex
defmodule JsTracker.Tracker.Recording do
  use Ecto.Schema
  import Ecto.Changeset
  alias JsTracker.Tracker.Recording

  schema "recordings" do
    field :changed, :boolean
    belongs_to :target, JsTracker.Tracker.Target
    many_to_many :resources, JsTracker.Tracker.Resource, join_through: "resources_recordings"

    timestamps()
  end

  @doc false
  def changeset(%Recording{} = recording, attrs, resources \\ []) do
    recording
    |> cast(attrs, [:target_id, :changed])
    |> put_assoc(:resources, resources)
    |> assoc_constraint(:target)
  end
end

lib/js_tracker_web/controllers/recording_controller.ex
defmodule JsTrackerWeb.RecordingController do
  use JsTrackerWeb, :controller

  alias JsTracker.Tracker
  alias JsTracker.Tracker.Recording

  def index(conn, params) do
    %{"target_id" => target_id} = params
    {recordings, kerosene} = Tracker.paginate_recordings(target_id, params)
    render(conn, "index.html", recordings: recordings, kerosene: kerosene)
  end
end

lib/js_tracker_web/views/recording_view.ex
defmodule JsTrackerWeb.RecordingView do
  use JsTrackerWeb, :view
  import Kerosene.HTML
end

lib/js_tracker_web/templates/recording/index.html.eex
<div class="row">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>
            Tracked at
          </th>
          <th>Changed</th>
          <th>Resources</th>
        </tr>
      </thead>
      <tbody>
        <%= for recording <- @recordings do %>
          <tr>
            <td><%= Elixir.Timex.Format.DateTime.Formatters.Relative.format!(recording.inserted_at, "{relative}") %></td>
            <td><%= recording.changed %></td>
            <td><%= link "Show resources", to: resource_path(@conn, :index, recording_id: recording.id), class: "btn btn-default btn-xs" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= paginate @conn, @kerosene %>